name: Introdução a demonstrações matemáticas
title: Introdução a demonstrações matemáticas | Um minicurso do PET/CC (UFRN)
description: Material utilizado no minicurso de introdução a demonstrações matemáticas
  ofertado pelo Programa de Educação Tutorial de Ciência da Computação (UFRN).
tags:
  - logic
  - UFRN
  - academic
  - mathematics
  - computer science
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
email: petcc@dimap.ufrn.br
# See: https://disqus.com/
disqus_username:
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id:
